// <auto-generated />
using System;
using Cao2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cao2.Migrations
{
    [DbContext(typeof(VatTuDbContext))]
    [Migration("20220306153240_v11")]
    partial class v11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Cao1.entities.BoPhan", b =>
                {
                    b.Property<int>("BoPhanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDungDau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenBoPhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BoPhanid");

                    b.ToTable("Bo Phan");

                    b.HasData(
                        new
                        {
                            BoPhanid = 1,
                            Ngaytao = new DateTime(2022, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungDau = "Nguyen Van A",
                            TenBoPhan = " Bo phan 1"
                        },
                        new
                        {
                            BoPhanid = 2,
                            Ngaytao = new DateTime(2022, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDungDau = "Nguyen Van B",
                            TenBoPhan = " Bo phan 2"
                        });
                });

            modelBuilder.Entity("Cao1.entities.DangKiMuaBan", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BoPhanid")
                        .HasColumnType("int");

                    b.Property<string>("TenMatHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Orderid");

                    b.HasIndex("BoPhanid");

                    b.ToTable("Dang Ki Mua Ban");

                    b.HasData(
                        new
                        {
                            Orderid = 1,
                            BoPhanid = 1,
                            TenMatHang = " Mat Hang 1"
                        },
                        new
                        {
                            Orderid = 2,
                            BoPhanid = 2,
                            TenMatHang = " Mat Hang 2"
                        });
                });

            modelBuilder.Entity("Cao1.entities.SanPham", b =>
                {
                    b.Property<int>("SanPhamid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DangKiMuaBanid")
                        .HasColumnType("int");

                    b.Property<string>("LoaiSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SanPhamid");

                    b.HasIndex("DangKiMuaBanid");

                    b.ToTable("San Pham");

                    b.HasData(
                        new
                        {
                            SanPhamid = 1,
                            DangKiMuaBanid = 1,
                            LoaiSanPham = "Loai 1",
                            SoLuong = 17,
                            TenSanPham = " San Pham 1"
                        },
                        new
                        {
                            SanPhamid = 2,
                            DangKiMuaBanid = 2,
                            LoaiSanPham = "Loai 2",
                            SoLuong = 29,
                            TenSanPham = " San Pham 2"
                        });
                });

            modelBuilder.Entity("Cao1.entities.DangKiMuaBan", b =>
                {
                    b.HasOne("Cao1.entities.BoPhan", "BoPhan")
                        .WithMany()
                        .HasForeignKey("BoPhanid");

                    b.Navigation("BoPhan");
                });

            modelBuilder.Entity("Cao1.entities.SanPham", b =>
                {
                    b.HasOne("Cao1.entities.DangKiMuaBan", "DangKiMuaBan")
                        .WithMany()
                        .HasForeignKey("DangKiMuaBanid");

                    b.Navigation("DangKiMuaBan");
                });
#pragma warning restore 612, 618
        }
    }
}
